using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlatformController : MonoBehaviour
{

    
    [HideInInspector] public bool jump = false;
    public float moveForce = 365f;
    public float maxSpeed = 5f;
    public float jumpForce = 1000f;
    public Transform groundCheck;
    //public GameObject DeathEffect;
    //public GameObject Floor;


    //private SpriteRenderer rend;
    private Rigidbody rigid;
    private bool grounded = false;
    //private Animator anim;
    private Rigidbody rb2d;

    void Start()
    {
        rigid = GetComponent<Rigidbody>();
        //anim = GetComponent<Animator>();
       // rend = GetComponent<SpriteRenderer>();
    }

    // Use this for initialization
    void Awake()
    {
       // anim = GetComponent<Animator>();
        rb2d = GetComponent<Rigidbody>();
    }

    // Update is called once per frame
    void Update()
    {
        rigid.AddForce(new Vector2(Input.GetAxis("Horizontal") * maxSpeed, 0), ForceMode.Force);
        //anim.SetFloat("HorizontalGo", Input.GetAxisRaw("Horizontal"));
        if (Input.GetAxisRaw("Horizontal") < -0.1f)
        {
            //flip sptite renderer
            //rend.flipX = true;
        }
        else
        {
            //unflip
            //rend.flipX = false;
        }
        //
        grounded = Physics.Linecast(transform.position, groundCheck.position, 1 << LayerMask.NameToLayer("Ground"));

        if (Input.GetButtonDown("Jump") && grounded)
        {
            jump = true;
        }
        else
        {
            jump = false;
        }
    }

    void FixedUpdate()
    {
        float h = Input.GetAxis("Horizontal");

        //anim.SetFloat("speed", Mathf.Abs(h));

        if (h * rb2d.velocity.x < maxSpeed)
            rb2d.AddForce(Vector2.right * h * moveForce);

        if (Mathf.Abs(rb2d.velocity.x) > maxSpeed)
            rb2d.velocity = new Vector2(Mathf.Sign(rb2d.velocity.x) * maxSpeed, rb2d.velocity.y);

        

        if (jump)
        {
            //anim.SetTrigger("Jump");
            rb2d.AddForce(new Vector2(0f, jumpForce));
            jump = false;
        }
    }

    private void OnTriggerEnter(Collider collider)
    {
        if (collider.gameObject.tag == "EVP")
        {
            // spawn cool effect
            //Instantiate(DeathEffect, transform.position, transform.rotation);
        }
    }
        

    /*void Flip()
    {
        facingRight = !facingRight;
        Vector3 theScale = transform.localScale;
        theScale.x *= -1;
        transform.localScale = theScale;
    }*/
}